services:
  
  pfun-django:
    build: ./app
    volumes:
      - ./app/:/app/
    env_file:
      - ./.env.dev
    environment:
      - REDIS_HOST=cache
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - cache

  cache: # new
    image: redis:8-bookworm
    restart: always
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"    
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local
