services:
  
  pfun-django:
    build: ./app
    volumes:
      - ./app/:/app/
    env_file:
      - ./.env.dev
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - cache
    
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    env_file:
      - ./.env.dev
volumes:
  cache:
    driver: local
